### ISSUE TITLE
error when clic on import

### ISSUE THREAD

**Issue by dureimatlecam** [jgrygierek/SonataBatchEntityImportBundle#10]
Hi, thanks for this great bundle.
Unfortunatly, i get this error when i clic on import:
There are no registered paths for namespace "SonataCore" in @SonataBatchEntityImport/select_file.html.twig
Do you have an idea ?
Regards

**Comment by jgrygierek** [comment]
Hi, I will check it. Probably it is related to the new changes in Sonata Admin (Core Bundle has been dropped).

**Comment by jgrygierek** [comment]
@dureimatlecam I added temporary fix. Please update package version and tell me if now it is ok.

**Comment by dureimatlecam** [comment]
Hi Jarek, thanks for your quick reply :) it works !
Many thanks !
